### ISSUE TITLE
Does this work inside SGX enclave ?

### ISSUE THREAD

**Issue by gmatesunny** [kaimast/libdocument#2]
Hi, Is your library work inside SGX enclave? Can I have a sample code?

**Comment by kaimast** [comment]
Yes! Just use the API as normal and link against the libdocument_sgx.a static library.

There's a bunch of examples on how to use the API in the test folder.

**Comment by gmatesunny** [comment]
I am on Ubuntu and I use Make. I cannot get libdocument_sgx.a.

**Comment by abcdabcd987** [comment]
`libdocument` uses [Meson](http://mesonbuild.com/) as the build system.

```bash
meson build
cd build
ninja
ninja install
```

**Comment by kaimast** [comment]
I'm going to close this issue after adding some more information about how to build this under SGX.
Feel free to reopen it if you have any more questions.

**Comment by gmatesunny** [comment]
No problem, I am able to link with your library. Sorry that I didn't close
it myself.

**Comment by gmatesunny** [comment]
It fails to build with the following error:
```
roshan@bolt:~/SGXcompliment/libdocument/build$ meson configure -Dcpp_std=c++17
roshan@bolt:~/SGXcompliment/libdocument/build$ ninja
[1/1] Regenerating build files.
The Meson build system
Version: 0.45.0
Source dir: /home/roshan/SGXcompliment/libdocument
Build dir: /home/roshan/SGXcompliment/libdocument/build
Build type: native build
Project name: libdocument
Native C++ compiler: c++ (gcc 5.4.1 "c++ (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency gtest found: YES (cached)
Dependency gmock found: YES (cached)
Library sgx_tstdc found: YES
Library sgx_tcxx found: YES
Library sgx_trts found: YES
Build targets in project: 3
Found ninja-1.5.1 at /usr/bin/ninja
[26/29] Linking target libdocument.so.
FAILED: c++  -o libdocument.so 'document@sha/src_Parser.cpp.o' 'document@sha/src_IterationEngine.cpp.o' 'document@sha/src_Writer.cpp.o' 'document@sha/src_Document.cpp.o' 'document@sha/src_Search.cpp.o' 'document@sha/src_Projection.cpp.o' 'document@sha/src_DocumentPrinter.cpp.o' 'document@sha/src_DocumentPrettyPrinter.cpp.o' 'document@sha/src_PredicateChecker.cpp.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libdocument.so -Wl,--end-group  
document@sha/src_Writer.cpp.o: In function `bitstream::resize(unsigned int)':
/usr/local/include/bitstream.h:150: undefined reference to `bitstream::MIN_REALLOC'
collect2: error: ld returned 1 exit status
[26/29] Compiling C++ object 'libdocument-test@exe/gtest-all.cc.o'.
ninja: build stopped: subcommand failed.
```
Please reopen the issue.

**Comment by kaimast** [comment]
You probably need to compile with the -std=c++17 flag :)

**Comment by gmatesunny** [comment]
I think I did, see:
roshan@bolt:~/SGXcompliment/libdocument/build$ meson configure -Dcpp_std=c++17

**Comment by kaimast** [comment]
Woops you're right. It's probably cause of your version of GCC then. I think you need at least gcc7 for the c++17 support. 

You could use this PPA to update GCC https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial

Or you could modify the bitstream header to define that constant differently...
